# Generated by Django 5.2.13 on 2026-04-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0003_invitation_token_uuid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patrolmatch',
            name='patrols_must_be_different',
        ),
        migrations.AddConstraint(
            model_name='patrolmatch',
            constraint=models.CheckConstraint(condition=models.Q(('patrol_a', models.F('patrol_b')), _negated=True), name='patrols_must_be_different'),
        ),
    ]
