# Generated by Django 5.2.13 on 2026-04-22 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0009_payment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='scouting_pa_patrol__23d8ba_idx',
            old_name='scouting_pay_patrol_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='scouting_pa_status_a4317b_idx',
            old_name='scouting_pay_status_idx',
        ),
    ]
