# Generated by Django 5.2.13 on 2026-04-22 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0013_stelocertification'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrol',
            name='is_rover_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PatrolYouTubeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField()),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('embed_url', models.URLField(blank=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Esperando validación'), ('valid', 'Validado'), ('invalid', 'No válido'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('audit_status', models.CharField(choices=[('pending', 'Auditando'), ('passed', 'Pasó auditoría'), ('failed', 'Falló auditoría'), ('manual_review', 'Revisión manual')], default='pending', max_length=20)),
                ('audit_errors', models.JSONField(blank=True, default=list)),
                ('audit_findings', models.JSONField(blank=True, default=dict)),
                ('leader_approval_status', models.CharField(choices=[('pending', 'Pendiente de aprobación'), ('approved', 'Siempre Listos (Aprobado)'), ('rejected', 'Rechazado por líder')], default='pending', max_length=20)),
                ('leader_approved_at', models.DateTimeField(blank=True, null=True)),
                ('leader_approval_notes', models.TextField(blank=True)),
                ('leader_notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('final_approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_for_wall_of_fame', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('audited_at', models.DateTimeField(blank=True, null=True)),
                ('patrol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_submission', to='scouting.patrol')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='RoverIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_by_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('priority', models.CharField(default='high', max_length=12)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('in_review', 'En revisión'), ('resolved', 'Resuelta')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('patrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rover_incidents', to='scouting.patrol')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='scouting_ro_status_08166d_idx'), models.Index(fields=['patrol', '-created_at'], name='scouting_ro_patrol__37acfe_idx')],
            },
        ),
    ]
