# Generated by Django 5.2.13 on 2026-04-22 04:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0015_patrol_mcer_notification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrol',
            name='leadership_project_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patrol',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patrol',
            name='onboarding_step',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patrol',
            name='telegram_node_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patrol',
            name='telegram_node_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='patrol',
            name='telegram_node_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='MCERCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcer_level', models.CharField(choices=[('A1', 'A1 Malkovranto (0-1,000 pts)'), ('A2', 'A2 Vojtrovanto (1,001-3,000 pts)'), ('B1', 'B1 Esploristo (3,001-6,000 pts)'), ('B2', 'B2 Gvidanto (6,001+ pts)')], max_length=2)),
                ('points_at_issue', models.PositiveIntegerField()),
                ('certification_code', models.CharField(max_length=60, unique=True)),
                ('qr_png_b64', models.TextField(blank=True)),
                ('pdf_file_path', models.CharField(blank=True, max_length=255)),
                ('preview_requested_count', models.PositiveIntegerField(default=0)),
                ('last_preview_requested_at', models.DateTimeField(blank=True, null=True)),
                ('leader_notified_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('match_start_date', models.DateField(blank=True, null=True)),
                ('patrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcer_certificates', to='scouting.patrol')),
                ('sister_patrol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcer_certificates_as_sister', to='scouting.patrol')),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['patrol', '-issued_at'], name='scouting_mc_patrol__26eaf5_idx'), models.Index(fields=['certification_code'], name='scouting_mc_certifi_b2d362_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatrolInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=40)),
                ('patrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='scouting.patrol')),
            ],
            options={
                'ordering': ['tag'],
                'constraints': [models.UniqueConstraint(fields=('patrol', 'tag'), name='unique_patrol_interest_tag')],
            },
        ),
        migrations.CreateModel(
            name='PatrolMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('alias', models.CharField(blank=True, max_length=80)),
                ('gender', models.CharField(choices=[('female', 'Femenino'), ('male', 'Masculino'), ('non_binary', 'No binario'), ('prefer_not_to_say', 'Prefiero no decir')], max_length=20)),
                ('birth_date', models.DateField()),
                ('initial_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2')], max_length=2)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('joined_node_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='scouting.patrol')),
            ],
            options={
                'ordering': ['full_name'],
                'constraints': [models.UniqueConstraint(fields=('patrol', 'full_name'), name='unique_member_name_per_patrol')],
            },
        ),
    ]
